### ISSUE TITLE
syn() and syns() are ill-behaved when a word doesn't exist

### ISSUE THREAD

**Issue by coolbutuseless** [ropenscilabs/syn#15]
`syn("xxxxx")`  # returns `NULL` rather than, say, `character(0)`
`syn("xxxxx", n_words = 10)` # causes error.

`syns()` is similarly broken.

**Comment by njtierney** [comment]
Yeah, I think that I'll just add to the documentation about what to expect. I think it's pretty reasonable that if you get `character(0)` you can reason that there are no synonyms available.

I'll work on this now.
